apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranbhumi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ranbhumi-backend
  template:
    metadata:
      labels:
        app: ranbhumi-backend
    spec:
      containers:
        - name: backend
          image: username/ranbhumi-backend
          ports:
            - containerPort: 8081
