apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranbhumi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranbhumi-frontend
  template:
    metadata:
      labels:
        app: ranbhumi-frontend
    spec:
      containers:
        - name: frontend
          image: username/ranbhumi-frontend
          ports:
            - containerPort: 3080
